set_property PACKAGE_PIN E3 [get_ports clk_100mhz]
set_property IOSTANDARD LVCMOS33 [get_ports clk_100mhz]
create_clock -period 10.000 -name sys_clk [get_ports clk_100mhz]
set_property PACKAGE_PIN N17 [get_ports btnC]
set_property IOSTANDARD LVCMOS33 [get_ports btnC]
set_property PACKAGE_PIN M18 [get_ports btnU]
set_property IOSTANDARD LVCMOS33 [get_ports btnU]
set_property PACKAGE_PIN J15 [get_ports {sw[0]}]
set_property PACKAGE_PIN L16 [get_ports {sw[1]}]
set_property PACKAGE_PIN M13 [get_ports {sw[2]}]
set_property PACKAGE_PIN R15 [get_ports {sw[3]}]
set_property PACKAGE_PIN R17 [get_ports {sw[4]}]
set_property PACKAGE_PIN T18 [get_ports {sw[5]}]
set_property PACKAGE_PIN U18 [get_ports {sw[6]}]
set_property PACKAGE_PIN R13 [get_ports {sw[7]}]
set_property PACKAGE_PIN T8 [get_ports {sw[8]}]
set_property PACKAGE_PIN U8 [get_ports {sw[9]}]
set_property PACKAGE_PIN R16 [get_ports {sw[10]}]
set_property PACKAGE_PIN T13 [get_ports {sw[11]}]
set_property PACKAGE_PIN H6 [get_ports {sw[12]}]
set_property PACKAGE_PIN U12 [get_ports {sw[13]}]
set_property PACKAGE_PIN U11 [get_ports {sw[14]}]
set_property PACKAGE_PIN V10 [get_ports {sw[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[*]}]
set_property PACKAGE_PIN H17 [get_ports {led[0]}]
set_property PACKAGE_PIN K15 [get_ports {led[1]}]
set_property PACKAGE_PIN J13 [get_ports {led[2]}]
set_property PACKAGE_PIN N14 [get_ports {led[3]}]
set_property PACKAGE_PIN R18 [get_ports {led[4]}]
set_property PACKAGE_PIN V17 [get_ports {led[5]}]
set_property PACKAGE_PIN U17 [get_ports {led[6]}]
set_property PACKAGE_PIN U16 [get_ports {led[7]}]
set_property PACKAGE_PIN V16 [get_ports {led[8]}]
set_property PACKAGE_PIN T15 [get_ports {led[9]}]
set_property PACKAGE_PIN U14 [get_ports {led[10]}]
set_property PACKAGE_PIN T16 [get_ports {led[11]}]
set_property PACKAGE_PIN V15 [get_ports {led[12]}]
set_property PACKAGE_PIN V14 [get_ports {led[13]}]
set_property PACKAGE_PIN V12 [get_ports {led[14]}]
set_property PACKAGE_PIN V11 [get_ports {led[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[*]}]
set_property PACKAGE_PIN T10 [get_ports {seg[0]}]
set_property PACKAGE_PIN R10 [get_ports {seg[1]}]
set_property PACKAGE_PIN K16 [get_ports {seg[2]}]
set_property PACKAGE_PIN K13 [get_ports {seg[3]}]
set_property PACKAGE_PIN P15 [get_ports {seg[4]}]
set_property PACKAGE_PIN T11 [get_ports {seg[5]}]
set_property PACKAGE_PIN L18 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[*]}]
set_property PACKAGE_PIN J17 [get_ports {an[0]}]
set_property PACKAGE_PIN J18 [get_ports {an[1]}]
set_property PACKAGE_PIN T9 [get_ports {an[2]}]
set_property PACKAGE_PIN J14 [get_ports {an[3]}]
set_property PACKAGE_PIN P14 [get_ports {an[4]}]
set_property PACKAGE_PIN T14 [get_ports {an[5]}]
set_property PACKAGE_PIN K2 [get_ports {an[6]}]
set_property PACKAGE_PIN U13 [get_ports {an[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an[*]}]
set_false_path -from [get_ports btnC]
set_false_path -from [get_ports btnU]
set_false_path -from [get_ports {sw[*]}]

create_generated_clock -name slow_clk -source [get_ports clk_100mhz] -divide_by 8 [get_pins clk_bufg_inst/O]
set_clock_groups -asynchronous -group [get_clocks slow_clk] -group [get_clocks sys_clk]
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_100mhz_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {processor/MEM_WB_IR[0]} {processor/MEM_WB_IR[1]} {processor/MEM_WB_IR[2]} {processor/MEM_WB_IR[3]} {processor/MEM_WB_IR[4]} {processor/MEM_WB_IR[5]} {processor/MEM_WB_IR[6]} {processor/MEM_WB_IR[7]} {processor/MEM_WB_IR[8]} {processor/MEM_WB_IR[9]} {processor/MEM_WB_IR[10]} {processor/MEM_WB_IR[11]} {processor/MEM_WB_IR[12]} {processor/MEM_WB_IR[13]} {processor/MEM_WB_IR[14]} {processor/MEM_WB_IR[15]} {processor/MEM_WB_IR[16]} {processor/MEM_WB_IR[17]} {processor/MEM_WB_IR[18]} {processor/MEM_WB_IR[19]} {processor/MEM_WB_IR[20]} {processor/MEM_WB_IR[21]} {processor/MEM_WB_IR[22]} {processor/MEM_WB_IR[23]} {processor/MEM_WB_IR[24]} {processor/MEM_WB_IR[25]} {processor/MEM_WB_IR[26]} {processor/MEM_WB_IR[27]} {processor/MEM_WB_IR[28]} {processor/MEM_WB_IR[29]} {processor/MEM_WB_IR[30]} {processor/MEM_WB_IR[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 10 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {processor/PC[0]} {processor/PC[1]} {processor/PC[2]} {processor/PC[3]} {processor/PC[4]} {processor/PC[5]} {processor/PC[6]} {processor/PC[7]} {processor/PC[8]} {processor/PC[9]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {processor/EX_MEM_B[0]} {processor/EX_MEM_B[1]} {processor/EX_MEM_B[2]} {processor/EX_MEM_B[3]} {processor/EX_MEM_B[4]} {processor/EX_MEM_B[5]} {processor/EX_MEM_B[6]} {processor/EX_MEM_B[7]} {processor/EX_MEM_B[8]} {processor/EX_MEM_B[9]} {processor/EX_MEM_B[10]} {processor/EX_MEM_B[11]} {processor/EX_MEM_B[12]} {processor/EX_MEM_B[13]} {processor/EX_MEM_B[14]} {processor/EX_MEM_B[15]} {processor/EX_MEM_B[16]} {processor/EX_MEM_B[17]} {processor/EX_MEM_B[18]} {processor/EX_MEM_B[19]} {processor/EX_MEM_B[20]} {processor/EX_MEM_B[21]} {processor/EX_MEM_B[22]} {processor/EX_MEM_B[23]} {processor/EX_MEM_B[24]} {processor/EX_MEM_B[25]} {processor/EX_MEM_B[26]} {processor/EX_MEM_B[27]} {processor/EX_MEM_B[28]} {processor/EX_MEM_B[29]} {processor/EX_MEM_B[30]} {processor/EX_MEM_B[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {processor/ID_EX_IR[0]} {processor/ID_EX_IR[1]} {processor/ID_EX_IR[2]} {processor/ID_EX_IR[3]} {processor/ID_EX_IR[4]} {processor/ID_EX_IR[5]} {processor/ID_EX_IR[6]} {processor/ID_EX_IR[7]} {processor/ID_EX_IR[8]} {processor/ID_EX_IR[9]} {processor/ID_EX_IR[10]} {processor/ID_EX_IR[11]} {processor/ID_EX_IR[12]} {processor/ID_EX_IR[13]} {processor/ID_EX_IR[14]} {processor/ID_EX_IR[15]} {processor/ID_EX_IR[16]} {processor/ID_EX_IR[17]} {processor/ID_EX_IR[18]} {processor/ID_EX_IR[19]} {processor/ID_EX_IR[20]} {processor/ID_EX_IR[21]} {processor/ID_EX_IR[22]} {processor/ID_EX_IR[23]} {processor/ID_EX_IR[24]} {processor/ID_EX_IR[25]} {processor/ID_EX_IR[26]} {processor/ID_EX_IR[27]} {processor/ID_EX_IR[28]} {processor/ID_EX_IR[29]} {processor/ID_EX_IR[30]} {processor/ID_EX_IR[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {processor/ID_EX_IMM[0]} {processor/ID_EX_IMM[1]} {processor/ID_EX_IMM[2]} {processor/ID_EX_IMM[3]} {processor/ID_EX_IMM[4]} {processor/ID_EX_IMM[5]} {processor/ID_EX_IMM[6]} {processor/ID_EX_IMM[7]} {processor/ID_EX_IMM[8]} {processor/ID_EX_IMM[9]} {processor/ID_EX_IMM[10]} {processor/ID_EX_IMM[11]} {processor/ID_EX_IMM[12]} {processor/ID_EX_IMM[13]} {processor/ID_EX_IMM[14]} {processor/ID_EX_IMM[15]} {processor/ID_EX_IMM[16]} {processor/ID_EX_IMM[17]} {processor/ID_EX_IMM[18]} {processor/ID_EX_IMM[19]} {processor/ID_EX_IMM[20]} {processor/ID_EX_IMM[21]} {processor/ID_EX_IMM[22]} {processor/ID_EX_IMM[23]} {processor/ID_EX_IMM[24]} {processor/ID_EX_IMM[25]} {processor/ID_EX_IMM[26]} {processor/ID_EX_IMM[27]} {processor/ID_EX_IMM[28]} {processor/ID_EX_IMM[29]} {processor/ID_EX_IMM[30]} {processor/ID_EX_IMM[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {processor/MEM_WB_ALU_OUT[0]} {processor/MEM_WB_ALU_OUT[1]} {processor/MEM_WB_ALU_OUT[2]} {processor/MEM_WB_ALU_OUT[3]} {processor/MEM_WB_ALU_OUT[4]} {processor/MEM_WB_ALU_OUT[5]} {processor/MEM_WB_ALU_OUT[6]} {processor/MEM_WB_ALU_OUT[7]} {processor/MEM_WB_ALU_OUT[8]} {processor/MEM_WB_ALU_OUT[9]} {processor/MEM_WB_ALU_OUT[10]} {processor/MEM_WB_ALU_OUT[11]} {processor/MEM_WB_ALU_OUT[12]} {processor/MEM_WB_ALU_OUT[13]} {processor/MEM_WB_ALU_OUT[14]} {processor/MEM_WB_ALU_OUT[15]} {processor/MEM_WB_ALU_OUT[16]} {processor/MEM_WB_ALU_OUT[17]} {processor/MEM_WB_ALU_OUT[18]} {processor/MEM_WB_ALU_OUT[19]} {processor/MEM_WB_ALU_OUT[20]} {processor/MEM_WB_ALU_OUT[21]} {processor/MEM_WB_ALU_OUT[22]} {processor/MEM_WB_ALU_OUT[23]} {processor/MEM_WB_ALU_OUT[24]} {processor/MEM_WB_ALU_OUT[25]} {processor/MEM_WB_ALU_OUT[26]} {processor/MEM_WB_ALU_OUT[27]} {processor/MEM_WB_ALU_OUT[28]} {processor/MEM_WB_ALU_OUT[29]} {processor/MEM_WB_ALU_OUT[30]} {processor/MEM_WB_ALU_OUT[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 32 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {processor/EX_MEM_ALU_OUT[0]} {processor/EX_MEM_ALU_OUT[1]} {processor/EX_MEM_ALU_OUT[2]} {processor/EX_MEM_ALU_OUT[3]} {processor/EX_MEM_ALU_OUT[4]} {processor/EX_MEM_ALU_OUT[5]} {processor/EX_MEM_ALU_OUT[6]} {processor/EX_MEM_ALU_OUT[7]} {processor/EX_MEM_ALU_OUT[8]} {processor/EX_MEM_ALU_OUT[9]} {processor/EX_MEM_ALU_OUT[10]} {processor/EX_MEM_ALU_OUT[11]} {processor/EX_MEM_ALU_OUT[12]} {processor/EX_MEM_ALU_OUT[13]} {processor/EX_MEM_ALU_OUT[14]} {processor/EX_MEM_ALU_OUT[15]} {processor/EX_MEM_ALU_OUT[16]} {processor/EX_MEM_ALU_OUT[17]} {processor/EX_MEM_ALU_OUT[18]} {processor/EX_MEM_ALU_OUT[19]} {processor/EX_MEM_ALU_OUT[20]} {processor/EX_MEM_ALU_OUT[21]} {processor/EX_MEM_ALU_OUT[22]} {processor/EX_MEM_ALU_OUT[23]} {processor/EX_MEM_ALU_OUT[24]} {processor/EX_MEM_ALU_OUT[25]} {processor/EX_MEM_ALU_OUT[26]} {processor/EX_MEM_ALU_OUT[27]} {processor/EX_MEM_ALU_OUT[28]} {processor/EX_MEM_ALU_OUT[29]} {processor/EX_MEM_ALU_OUT[30]} {processor/EX_MEM_ALU_OUT[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 32 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {processor/IF_ID_IR[0]} {processor/IF_ID_IR[1]} {processor/IF_ID_IR[2]} {processor/IF_ID_IR[3]} {processor/IF_ID_IR[4]} {processor/IF_ID_IR[5]} {processor/IF_ID_IR[6]} {processor/IF_ID_IR[7]} {processor/IF_ID_IR[8]} {processor/IF_ID_IR[9]} {processor/IF_ID_IR[10]} {processor/IF_ID_IR[11]} {processor/IF_ID_IR[12]} {processor/IF_ID_IR[13]} {processor/IF_ID_IR[14]} {processor/IF_ID_IR[15]} {processor/IF_ID_IR[16]} {processor/IF_ID_IR[17]} {processor/IF_ID_IR[18]} {processor/IF_ID_IR[19]} {processor/IF_ID_IR[20]} {processor/IF_ID_IR[21]} {processor/IF_ID_IR[22]} {processor/IF_ID_IR[23]} {processor/IF_ID_IR[24]} {processor/IF_ID_IR[25]} {processor/IF_ID_IR[26]} {processor/IF_ID_IR[27]} {processor/IF_ID_IR[28]} {processor/IF_ID_IR[29]} {processor/IF_ID_IR[30]} {processor/IF_ID_IR[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 32 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {processor/ID_EX_NPC[0]} {processor/ID_EX_NPC[1]} {processor/ID_EX_NPC[2]} {processor/ID_EX_NPC[3]} {processor/ID_EX_NPC[4]} {processor/ID_EX_NPC[5]} {processor/ID_EX_NPC[6]} {processor/ID_EX_NPC[7]} {processor/ID_EX_NPC[8]} {processor/ID_EX_NPC[9]} {processor/ID_EX_NPC[10]} {processor/ID_EX_NPC[11]} {processor/ID_EX_NPC[12]} {processor/ID_EX_NPC[13]} {processor/ID_EX_NPC[14]} {processor/ID_EX_NPC[15]} {processor/ID_EX_NPC[16]} {processor/ID_EX_NPC[17]} {processor/ID_EX_NPC[18]} {processor/ID_EX_NPC[19]} {processor/ID_EX_NPC[20]} {processor/ID_EX_NPC[21]} {processor/ID_EX_NPC[22]} {processor/ID_EX_NPC[23]} {processor/ID_EX_NPC[24]} {processor/ID_EX_NPC[25]} {processor/ID_EX_NPC[26]} {processor/ID_EX_NPC[27]} {processor/ID_EX_NPC[28]} {processor/ID_EX_NPC[29]} {processor/ID_EX_NPC[30]} {processor/ID_EX_NPC[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 32 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {processor/EX_MEM_IR[0]} {processor/EX_MEM_IR[1]} {processor/EX_MEM_IR[2]} {processor/EX_MEM_IR[3]} {processor/EX_MEM_IR[4]} {processor/EX_MEM_IR[5]} {processor/EX_MEM_IR[6]} {processor/EX_MEM_IR[7]} {processor/EX_MEM_IR[8]} {processor/EX_MEM_IR[9]} {processor/EX_MEM_IR[10]} {processor/EX_MEM_IR[11]} {processor/EX_MEM_IR[12]} {processor/EX_MEM_IR[13]} {processor/EX_MEM_IR[14]} {processor/EX_MEM_IR[15]} {processor/EX_MEM_IR[16]} {processor/EX_MEM_IR[17]} {processor/EX_MEM_IR[18]} {processor/EX_MEM_IR[19]} {processor/EX_MEM_IR[20]} {processor/EX_MEM_IR[21]} {processor/EX_MEM_IR[22]} {processor/EX_MEM_IR[23]} {processor/EX_MEM_IR[24]} {processor/EX_MEM_IR[25]} {processor/EX_MEM_IR[26]} {processor/EX_MEM_IR[27]} {processor/EX_MEM_IR[28]} {processor/EX_MEM_IR[29]} {processor/EX_MEM_IR[30]} {processor/EX_MEM_IR[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list processor/HALTED]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list processor/TAKEN_BRANCH]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_100mhz_IBUF_BUFG]
